const $=id=>document.getElementById(id);
const zipInput=$('zipInput'),zipInfo=$('zipInfo'),zipConvert=$('zipConvert'),zipStatus=$('zipStatus'),zipDownload=$('zipDownload');
const pdfInput=$('pdfInput'),pdfInfo=$('pdfInfo'),analyzeBtn=$('analyzeBtn'),orgStatus=$('organizerStatus'),autoPanel=$('autoPanel'),manualPanel=$('manualPanel'),autoList=$('autoList'),manualList=$('manualList'),recreateAuto=$('recreateAuto'),recreateManual=$('recreateManual'),orgDownload=$('organizerDownload');
let zipFile=null,pdfFile=null,pdfBytes=null,pageData=[],autoOrder=[],manualOrder=[],mode='auto';
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active')});
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;if(pageData.length){autoPanel.classList.toggle('hidden',mode!=='auto');manualPanel.classList.toggle('hidden',mode!=='manual')}});
const size=n=>n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB';
function msg(el,t,c=''){el.textContent=t;el.className='status '+c}
function ext(n){let i=n.lastIndexOf('.');return i<0?'':n.slice(i+1).toLowerCase()}
zipInput.onchange=()=>{zipFile=zipInput.files[0];zipConvert.disabled=!zipFile;zipDownload.classList.add('hidden');if(!zipFile){zipInfo.textContent='No ZIP selected.';return}if(!zipFile.name.toLowerCase().endsWith('.zip')){zipFile=null;zipConvert.disabled=true;zipInfo.textContent='Please choose a .zip file.';msg(zipStatus,'Only .zip files are accepted.','err');return}if(zipFile.size>500*1024*1024){zipFile=null;zipConvert.disabled=true;zipInfo.textContent='ZIP is too large.';msg(zipStatus,'Maximum size is 500 MB.','err');return}zipInfo.textContent=zipFile.name+' — '+size(zipFile.size);msg(zipStatus,'ZIP selected. Tap Convert ZIP to PDF.','ok')};
zipConvert.onclick=async()=>{if(!zipFile)return;zipConvert.disabled=true;try{msg(zipStatus,'Reading ZIP...');const z=await JSZip.loadAsync(zipFile),entries=Object.values(z.files).filter(e=>!e.dir&&!e.name.startsWith('__MACOSX/')).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));const out=await PDFLib.PDFDocument.create();let ok=0,skip=0;for(const e of entries){let x=ext(e.name);try{if(x==='pdf'){let b=await e.async('uint8array'),src=await PDFLib.PDFDocument.load(b);(await out.copyPages(src,src.getPageIndices())).forEach(p=>out.addPage(p));ok++}else if(['jpg','jpeg','png'].includes(x)){let b=await e.async('uint8array'),im=x==='png'?await out.embedPng(b):await out.embedJpg(b),p=out.addPage([595.28,841.89]),s=Math.min(555/im.width,801/im.height),w=im.width*s,h=im.height*s;p.drawImage(im,{x:(595.28-w)/2,y:(841.89-h)/2,width:w,height:h});ok++}else skip++}catch(e){skip++}}if(!out.getPageCount())throw Error('No PDF or supported image files were found.');let bytes=await out.save(),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));zipDownload.href=url;zipDownload.classList.remove('hidden');msg(zipStatus,`Done. ${ok} file(s) converted${skip?' and '+skip+' skipped.':''}`,'ok')}catch(e){msg(zipStatus,'Conversion failed: '+e.message,'err')}finally{zipConvert.disabled=false}};
pdfInput.onchange=()=>{pdfFile=pdfInput.files[0];pdfBytes=null;pageData=[];analyzeBtn.disabled=!pdfFile;orgDownload.classList.add('hidden');autoPanel.classList.add('hidden');manualPanel.classList.add('hidden');if(pdfFile){pdfInfo.textContent=pdfFile.name+' — '+size(pdfFile.size);msg(orgStatus,'PDF selected. Choose Automatic or Manual, then Analyze PDF.','ok')}else pdfInfo.textContent='No PDF selected.'};
async function loadText(bytes){const pdf=await pdfjsLib.getDocument({data:bytes}).promise,arr=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),c=await p.getTextContent();arr.push({page:i,text:c.items.map(x=>x.str).join(' ')});if(i%10===0)msg(orgStatus,`Reading page text: ${i}/${pdf.numPages}`)}return arr}
function score(t){let s=t.replace(/\s+/g,' '),m=s.match(/(?:chapter|ch\.?|topic|unit|lesson|section|part)\s*[-.:]?\s*(\d{1,3})/i);if(m)return [+m[1],0];m=s.match(/^\s*(\d{1,3})\s*[.)\-:]\s+/);return m?[+m[1],0]:[9999,1]}
function title(d){let s=d.text.replace(/\s+/g,' ').trim();return s?s.slice(0,90)+(s.length>90?'…':''):`Page ${d.page}`}
function safe(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
analyzeBtn.onclick=async()=>{analyzeBtn.disabled=true;try{pdfBytes=new Uint8Array(await pdfFile.arrayBuffer());pageData=await loadText(pdfBytes);autoOrder=pageData.map((d,i)=>({d,i,k:score(d.text)})).sort((a,b)=>a.k[0]-b.k[0]||a.k[1]-b.k[1]||a.i-b.i).map(x=>x.i);manualOrder=pageData.map((_,i)=>i);renderAuto();renderManual();autoPanel.classList.toggle('hidden',mode!=='auto');manualPanel.classList.toggle('hidden',mode!=='manual');recreateAuto.disabled=false;recreateManual.disabled=false;msg(orgStatus,`Analyzed ${pageData.length} page(s). Review the proposed order.`,'ok')}catch(e){msg(orgStatus,'Could not analyze PDF: '+e.message,'err')}finally{analyzeBtn.disabled=false}};
function renderAuto(){autoList.innerHTML=autoOrder.map((idx,i)=>`<div class="item"><div class="item-main"><div class="item-title">${i+1}. ${safe(title(pageData[idx]))}</div><div class="item-meta">Original page ${pageData[idx].page}</div></div></div>`).join('')}
function renderManual(){manualList.innerHTML='';manualOrder.forEach((idx,i)=>{let d=pageData[idx],el=document.createElement('div');el.className='item';el.innerHTML=`<div class="item-main"><div class="item-title">${i+1}. ${safe(title(d))}</div><div class="item-meta">Original page ${d.page}</div></div><button class="move" data-u="${i}">↑</button><button class="move" data-d="${i}">↓</button>`;manualList.appendChild(el)});manualList.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>move(+b.dataset.u,-1));manualList.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>move(+b.dataset.d,1))}
function move(i,d){let j=i+d;if(j<0||j>=manualOrder.length)return;[manualOrder[i],manualOrder[j]]=[manualOrder[j],manualOrder[i]];renderManual()}
recreateAuto.onclick=()=>recreate(autoOrder);recreateManual.onclick=()=>recreate(manualOrder);
async function recreate(order){try{recreateAuto.disabled=true;recreateManual.disabled=true;msg(orgStatus,'Recreating PDF...');const src=await PDFLib.PDFDocument.load(pdfBytes),out=await PDFLib.PDFDocument.create(),pages=await out.copyPages(src,order);pages.forEach(p=>out.addPage(p));const bytes=await out.save(),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));orgDownload.href=url;orgDownload.download='organized-'+pdfFile.name;orgDownload.classList.remove('hidden');msg(orgStatus,'Done. Tap Download Organized PDF.','ok')}catch(e){msg(orgStatus,'Could not recreate PDF: '+e.message,'err')}finally{recreateAuto.disabled=false;recreateManual.disabled=false}}