const input=document.getElementById('zipInput'),info=document.getElementById('fileInfo'),btn=document.getElementById('convertBtn'),status=document.getElementById('status'),down=document.getElementById('downloadBtn'),box=document.getElementById('progressBox'),bar=document.getElementById('progress'),pt=document.getElementById('progressText');let file=null;
const imgs=new Set(['jpg','jpeg','png','gif','bmp','webp','svg']), texts=new Set(['txt','csv','html','htm','xml','json','md','log']);
const ext=n=>{let i=n.toLowerCase().lastIndexOf('.');return i<0?'':n.slice(i+1).split('?')[0]}; const size=n=>n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB';
function msg(t,c=''){status.textContent=t;status.className=c} function prog(n,t){bar.style.width=n+'%';pt.textContent=t}
input.onchange=()=>{file=input.files[0];down.classList.add('hidden');msg('');if(!file)return;if(!file.name.toLowerCase().endsWith('.zip')){file=null;btn.disabled=true;info.textContent='Please choose a .zip file.';msg('Only .zip files are accepted.','err');return}if(file.size>524288000){file=null;btn.disabled=true;info.textContent='ZIP is '+size(input.files[0].size);msg('Maximum size is 500 MB.','err');return}info.textContent=file.name+' — '+size(file.size);btn.disabled=false;msg('ZIP selected. Tap “Convert ZIP to PDF”.','ok')};
btn.onclick=async()=>{if(!file)return;btn.disabled=true;box.classList.remove('hidden');down.classList.add('hidden');try{msg('Opening ZIP...');prog(2,'Reading ZIP...');const z=await JSZip.loadAsync(file);const entries=Object.values(z.files).filter(x=>!x.dir&&!x.name.startsWith('__MACOSX/')).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));if(!entries.length)throw Error('The ZIP contains no files.');const out=await PDFLib.PDFDocument.create();let done=0,skip=[];for(let i=0;i<entries.length;i++){let e=entries[i],x=ext(e.name);prog(Math.round(i/entries.length*90),`Processing ${i+1} of ${entries.length}: ${e.name}`);try{if(x==='pdf'){let b=await e.async('uint8array'),src=await PDFLib.PDFDocument.load(b);(await out.copyPages(src,src.getPageIndices())).forEach(p=>out.addPage(p));done++}else if(imgs.has(x)){let b=await e.async('uint8array');await imagePage(out,b,x);done++}else if(texts.has(x)){let t=await e.async('text');textPages(out,e.name,t);done++}else skip.push(e.name)}catch(err){skip.push(e.name+' (could not read)')}}if(!out.getPageCount())throw Error('No supported files were found.');prog(96,'Creating PDF...');let bytes=await out.save(),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));down.href=url;down.classList.remove('hidden');prog(100,'Done');msg(`Success: ${done} file(s) converted.${skip.length?' '+skip.length+' unsupported file(s) skipped.':''}`,skip.length?'warn':'ok')}catch(e){prog(0,'Failed');msg('Conversion failed: '+e.message,'err')}finally{btn.disabled=false}};
async function imagePage(pdf,b,x){let im;if(x==='jpg'||x==='jpeg')im=await pdf.embedJpg(b);else if(x==='png')im=await pdf.embedPng(b);else{let blob=new Blob([b],{type:{gif:'image/gif',bmp:'image/bmp',webp:'image/webp',svg:'image/svg+xml'}[x]||'image/*'}),url=await read(blob);let png=await canvasPNG(url);im=await pdf.embedPng(png)}let W=595.28,H=841.89,p=pdf.addPage([W,H]),s=Math.min((W-40)/im.width,(H-40)/im.height),w=im.width*s,h=im.height*s;p.drawImage(im,{x:(W-w)/2,y:(H-h)/2,width:w,height:h})}
function read(b){return new Promise((r,j)=>{let f=new FileReader();f.onload=()=>r(f.result);f.onerror=j;f.readAsDataURL(b)})}
function canvasPNG(src){return new Promise((r,j)=>{let im=new Image();im.onload=()=>{let c=document.createElement('canvas'),s=Math.min(1,3000/Math.max(im.width,im.height));c.width=Math.max(1,im.width*s);c.height=Math.max(1,im.height*s);let q=c.getContext('2d');q.fillStyle='#fff';q.fillRect(0,0,c.width,c.height);q.drawImage(im,0,0,c.width,c.height);c.toBlob(async b=>r(new Uint8Array(await b.arrayBuffer())),'image/png')};im.onerror=()=>j(Error('Image could not be decoded.'));im.src=src})}
function textPages(pdf,name,text){let W=595.28,H=841.89,m=42,y=H-m,p=pdf.addPage([W,H]),lines=[];String(text).replace(/\r\n/g,'\n').replace(/\r/g,'\n').split('\n').forEach(l=>{if(!l)lines.push('');else for(let i=0;i<l.length;i+=95)lines.push(l.slice(i,i+95))});p.drawText(name.slice(0,90),{x:m,y,size:13,font:PDFLib.StandardFonts.HelveticaBold});y-=25;for(let l of lines){if(y<m){p=pdf.addPage([W,H]);y=H-m}p.drawText(l.slice(0,110),{x:m,y,size:9,font:PDFLib.StandardFonts.Helvetica});y-=13}}